openapi: "3.0.0"
info:
  version: 1.0.0
  title: geeq-api
paths:
  /auth/oauth:
    post:
      requestBody:
        description: ''
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/OauthPostRequestBody'
        required: true
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/OauthPostOkResponse"
          headers:
            Set-Cookie:
              schema:
                type: string
                example: geeq-session-id=abcde12345; Path=/; HttpOnly
  # /auth/me:
  #   get:

components:
  schemas:
    OauthPostRequestBody:
      properties:
        code:
          type: string
      required:
        - code
    OauthPostOkResponse:
      properties:
        message:
          type: string
      required:
        - message

  # /auth/logout:
  #   post:
  # /task:
  #   get:
  # /task/{taskId}:
  #   get:
  # /task/{taskId}/submission:
  #   post:
  # /task/{taskId}/submission:
  #   get:
