openapi: "3.0.0"
info:
  version: 1.0.0
  title: geeq-api
paths:
  /auth/login:
    $ref: "./openapi/auth-login.yaml"
  /auth/logout:
    $ref: "./openapi/auth-logout.yaml"
  /auth/me:
    $ref: "./openapi/auth-me.yaml"
  /task:
    $ref: "./openapi/task.yaml"
  /task/{taskId}:
    $ref: "./openapi/task-taskid.yaml"
