[package]
name = "domain"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
uuid = "1.8.0"
once_cell = "1.19.0"
axum-extra = { version = "0.9.2", features = ["cookie"] }
